// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkdayManagement_API.Models;

namespace WorkdayManagement_API.Migrations
{
    [DbContext(typeof(WorkDBContext))]
    partial class WorkDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WorkdayManagement_API.Models.Goals", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AccomplishDate")
                        .HasColumnName("AccomplishDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("AccomplishGoals")
                        .HasColumnName("AccomplishGoals")
                        .HasColumnType("bit");

                    b.Property<int>("DailyDoors")
                        .HasColumnName("DailyDoors")
                        .HasColumnType("int");

                    b.Property<int>("WorkerId")
                        .HasColumnName("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("WorkdayManagement_API.Models.Work", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfWork")
                        .HasColumnName("DateOfWork")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeplatedDoors")
                        .HasColumnName("DeplatedDoors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkerEnergyUnits")
                        .HasColumnName("WorkerEnergyUnits")
                        .HasColumnType("int");

                    b.Property<int>("WorkerId")
                        .HasColumnName("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Work");
                });
#pragma warning restore 612, 618
        }
    }
}
