// <auto-generated />
using System;
using DoorsApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DoorsApi.Migrations
{
    [DbContext(typeof(DoorsDBContext))]
    partial class DoorsDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DoorsApi.Models.Door", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Available")
                        .HasColumnName("Available")
                        .HasColumnType("bit");

                    b.Property<int>("Energy")
                        .HasColumnName("Energy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUsed")
                        .HasColumnName("LastUsed")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Doors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Available = true,
                            Energy = 30
                        },
                        new
                        {
                            Id = 2,
                            Available = true,
                            Energy = 40
                        },
                        new
                        {
                            Id = 3,
                            Available = true,
                            Energy = 20
                        },
                        new
                        {
                            Id = 4,
                            Available = true,
                            Energy = 15
                        },
                        new
                        {
                            Id = 5,
                            Available = true,
                            Energy = 25
                        },
                        new
                        {
                            Id = 6,
                            Available = true,
                            Energy = 10
                        },
                        new
                        {
                            Id = 7,
                            Available = true,
                            Energy = 20
                        },
                        new
                        {
                            Id = 8,
                            Available = true,
                            Energy = 30
                        },
                        new
                        {
                            Id = 9,
                            Available = true,
                            Energy = 10
                        },
                        new
                        {
                            Id = 10,
                            Available = true,
                            Energy = 15
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
